---
# Audio streaming handlers

- name: Restart alsa
  become: true
  ansible.builtin.systemd:
    name: alsa-restore.service
    state: restarted
  listen: restart alsa

- name: Restart icecast2
  become: true
  ansible.builtin.systemd:
    name: icecast2
    state: restarted
  listen: restart icecast2

- name: Restart liquidsoap
  become: true
  ansible.builtin.systemd:
    name: "{{ liqs_name }}_liquidsoap.service"
    state: restarted
    daemon_reload: true
  when: not (is_test_environment | default(false))
  listen: restart liquidsoap

- name: Restart detect_audio
  become: true
  ansible.builtin.systemd:
    name: detect_audio
    state: restarted
  when: not (is_test_environment | default(false))
  listen: restart detect_audio
