#!/bin/sh
# POSIX-compliant System Health Check
# Works on both Linux (Debian) and FreeBSD

set -u

# Color codes (POSIX compatible)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Detect OS type
OS_TYPE="unknown"
if [ -f /etc/debian_version ]; then
    OS_TYPE="debian"
elif [ "$(uname)" = "FreeBSD" ]; then
    OS_TYPE="freebsd"
elif [ -f /etc/redhat-release ]; then
    OS_TYPE="redhat"
fi

# Configuration
THRESHOLD_CPU=80
THRESHOLD_MEM=90
THRESHOLD_DISK=85

# Optional per-host configuration, written by
# ansible/playbooks/deploy_monitoring.yml from the inventory. Currently carries
# CRITICAL_SERVICES; see check_services. Absent is normal and fine — every
# setting it can carry has a working default below.
#
# Two paths because opnsense keeps local configuration under /usr/local/etc,
# and everything under /etc there is liable to be regenerated by the firewall.
CRITICAL_SERVICES="${CRITICAL_SERVICES:-}"
for _conf in "${HEALTH_CHECK_CONF:-}" /usr/local/etc/monitoring/health_check.conf /etc/monitoring/health_check.conf; do
    if [ -n "$_conf" ] && [ -r "$_conf" ]; then
        # shellcheck source=/dev/null
        . "$_conf"
        break
    fi
done

# Functions
print_status() {
    status="$1"
    message="$2"
    
    case "$status" in
        success)
            printf "${GREEN}✅${NC} %s\n" "$message"
            ;;
        warning)
            printf "${YELLOW}⚠️${NC} %s\n" "$message"
            ;;
        error)
            printf "${RED}❌${NC} %s\n" "$message"
            ;;
        *)
            printf "%s\n" "$message"
            ;;
    esac
}

check_uptime() {
    echo "=== System Uptime ==="
    uptime_output=$(uptime)
    print_status "success" "Uptime: $uptime_output"
    echo ""
    return 0
}

check_disk_usage() {
    echo "=== Disk Usage ==="
    issues=0

    # The loop is fed by a here-document rather than a pipeline. `df | grep |
    # while` runs the loop body in a subshell, so every increment to `issues`
    # would be discarded when it exits — the check would report a full disk on
    # screen and still return 0, which is the exact class of bug this script
    # had for its whole life. Here-doc redirection keeps the loop in the
    # current shell, so the count survives.
    disk_lines=$(df -h 2>/dev/null | grep -E '^(/dev/|tank/|zroot/|rpool/)')

    while IFS= read -r line; do
        [ -n "$line" ] || continue

        usage=$(echo "$line" | awk '{print $5}' | sed 's/%//')
        mount=$(echo "$line" | awk '{print $6}')

        # A non-numeric usage would make `[ -gt ]` fail and, under `set -u`
        # with no `set -e`, silently skip the comparison.
        case "$usage" in
            ''|*[!0-9]*)
                print_status "warning" "Disk ${mount:-?}: could not parse usage from: $line"
                continue
                ;;
        esac

        if [ "$usage" -gt "$THRESHOLD_DISK" ]; then
            print_status "error" "Disk $mount: ${usage}% (above ${THRESHOLD_DISK}%)"
            issues=$((issues + 1))
        elif [ "$usage" -gt $((THRESHOLD_DISK - 10)) ]; then
            print_status "warning" "Disk $mount: ${usage}%"
        else
            print_status "success" "Disk $mount: ${usage}%"
        fi
    done <<EOF
$disk_lines
EOF

    echo ""
    return $issues
}

check_memory() {
    echo "=== Memory Usage ==="
    issues=0

    if [ "$OS_TYPE" = "debian" ]; then
        # Linux memory check
        mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
        mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
        
        if [ "$mem_total" -gt 0 ]; then
            mem_used=$((mem_total - mem_available))
            mem_percent=$((mem_used * 100 / mem_total))
            
            if [ "$mem_percent" -gt "$THRESHOLD_MEM" ]; then
                print_status "error" "Memory: ${mem_percent}% used (above ${THRESHOLD_MEM}%)"
                issues=$((issues + 1))
            elif [ "$mem_percent" -gt $((THRESHOLD_MEM - 10)) ]; then
                print_status "warning" "Memory: ${mem_percent}% used"
            else
                print_status "success" "Memory: ${mem_percent}% used"
            fi
        fi
    elif [ "$OS_TYPE" = "freebsd" ]; then
        # FreeBSD memory check
        mem_info=$(sysctl -n hw.physmem hw.usermem 2>/dev/null)
        if [ -n "$mem_info" ]; then
            print_status "success" "Memory check completed (FreeBSD)"
        fi
    else
        print_status "warning" "Memory check not available for $OS_TYPE"
    fi
    echo ""
    return $issues
}

# Ask the kernel for the load rather than parsing `uptime` prose. The parse was
# wrong on FreeBSD for the entire life of this script: it stripped with
# `s/.*load average://` while FreeBSD prints `load averages:` — plural — so
# nothing was stripped and `awk '{print $1}'` returned the first field of the
# whole uptime line, which is the clock. Measured on opnsense 2026-08-05:
# `❌ Load: 12:27AM on 6 CPUs (200%)` against real averages of 0.24, the 200%
# being awk coercing `12:27AM` to 12 and dividing by 6 CPUs.
read_load_1min() {
    if [ -r /proc/loadavg ]; then
        awk '{print $1}' /proc/loadavg
        return
    fi

    if [ "$OS_TYPE" = "freebsd" ]; then
        # `{ 0.24 0.25 0.24 }` — the braces are fields 1 and 5.
        sysctl -n vm.loadavg 2>/dev/null | awk '{print $2}'
        return
    fi

    # Last resort, for a host with neither. Handles `load average:` and
    # FreeBSD's `load averages:`, and drops the thousands/decimal comma that
    # Linux appends between the three figures.
    uptime | sed -n 's/.*load averages*: *//p' | awk '{print $1}' | tr -d ','
}

check_load() {
    echo "=== System Load ==="
    issues=0

    # Get number of CPUs
    if [ "$OS_TYPE" = "freebsd" ]; then
        cpu_count=$(sysctl -n hw.ncpu)
    else
        cpu_count=$(nproc 2>/dev/null || grep -c ^processor /proc/cpuinfo 2>/dev/null || echo 1)
    fi

    load_avg=$(read_load_1min)

    # Validate what the read *yielded*, not that some pattern matched. This is
    # the guard that was missing: `12:27AM` survived the old parse, and the
    # existing check below only saw the percentage — `200` — which is a
    # perfectly plausible integer.
    case "$load_avg" in
        ''|*[!0-9.]*|*.*.*)
            print_status "warning" "Load: could not read load average (got '${load_avg}')"
            echo ""
            return 0
            ;;
    esac

    # Convert to percentage (rough estimate)
    load_percent=$(echo "$load_avg $cpu_count" | awk '{printf "%.0f", ($1/$2)*100}')

    case "$load_percent" in
        ''|*[!0-9]*)
            print_status "warning" "Load: could not compute load percentage (got '${load_avg}' on '${cpu_count}' CPUs)"
            echo ""
            return 0
            ;;
    esac

    if [ "$load_percent" -gt "$THRESHOLD_CPU" ]; then
        print_status "error" "Load: ${load_avg} on ${cpu_count} CPUs (${load_percent}%)"
        issues=$((issues + 1))
    elif [ "$load_percent" -gt $((THRESHOLD_CPU - 20)) ]; then
        print_status "warning" "Load: ${load_avg} on ${cpu_count} CPUs (${load_percent}%)"
    else
        print_status "success" "Load: ${load_avg} on ${cpu_count} CPUs"
    fi
    echo ""
    return $issues
}

# Stock FreeBSD's ssh rc script is `sshd`; OPNsense's is `openssh` — which the
# repo already knows, in ssh_hardening's `service openssh onereload`. Probing
# for the rc script answers the question directly, without the script needing
# to know what OPNsense is, and without renaming `sshd` fleet-wide: a blanket
# rename fixes the one firewall here and breaks stock FreeBSD, i.e. the §8b
# test VM that exists to catch exactly this.
freebsd_default_services() {
    for _dir in /etc/rc.d /usr/local/etc/rc.d; do
        if [ -f "$_dir/openssh" ]; then
            echo "openssh:sshd cron"
            return
        fi
    done
    echo "sshd cron"
}

# `service <name> status` answers from the rc script, and several of those read
# a root-owned pidfile — so an unprivileged caller is told a running daemon is
# not running. The health-check cron runs as the infrastructure user, so that
# is the answer the fleet has been getting. Measured on opnsense 2026-08-05:
# `❌ cron: not running` as choco and `✅` as root, seconds apart.
#
# The process table is not permission-dependent, so consult it when the rc
# script declines to answer. A genuinely dead daemon still fails both.
freebsd_service_running() {
    _svc="$1"
    _proc="$2"

    service "$_svc" status >/dev/null 2>&1 && return 0
    pgrep -x "$_proc" >/dev/null 2>&1 && return 0
    return 1
}

check_services() {
    echo "=== Critical Services ==="
    issues=0

    # The list is inventory-driven: a host that runs something else, or calls
    # it something else, says so in inventory rather than here (see
    # CRITICAL_SERVICES at the top and ansible/playbooks/deploy_monitoring.yml).
    # The built-in lists remain the default for a host with no config file yet
    # — the script must stay correct on its own, since it is deployed by a
    # different task than its configuration.
    #
    # An entry is `service[:process]`. The process name is only used on
    # FreeBSD, and only as the fallback described above.
    services="$CRITICAL_SERVICES"

    if [ "$OS_TYPE" = "debian" ]; then
        [ -n "$services" ] || services="ssh cron fail2ban"

        for entry in $services; do
            svc="${entry%%:*}"
            if systemctl is-active "$svc" >/dev/null 2>&1; then
                print_status "success" "Service $svc: running"
            else
                print_status "error" "Service $svc: not running"
                issues=$((issues + 1))
            fi
        done
    elif [ "$OS_TYPE" = "freebsd" ]; then
        [ -n "$services" ] || services=$(freebsd_default_services)

        for entry in $services; do
            svc="${entry%%:*}"
            proc="${entry#*:}"
            if freebsd_service_running "$svc" "$proc"; then
                print_status "success" "Service $svc: running"
            else
                print_status "error" "Service $svc: not running"
                issues=$((issues + 1))
            fi
        done
    else
        print_status "warning" "Service check not configured for $OS_TYPE"
    fi
    echo ""
    return $issues
}

# Named services are not enough on their own: CT 103 sat with 19 failed units,
# systemd-journald among them, and passed every check it had. A dead journald
# is what turned a 12-day monitoring outage into an unrecorded one — and it
# also makes fail2ban decorative, since its sshd filter reads the journal.
check_failed_units() {
    echo "=== Failed systemd Units ==="
    issues=0

    if [ "$OS_TYPE" != "debian" ] || ! command -v systemctl >/dev/null 2>&1; then
        print_status "warning" "Failed-unit check only available on systemd hosts"
        echo ""
        return 0
    fi

    failed_units=$(systemctl list-units --failed --no-legend --plain 2>/dev/null | awk '{print $1}')
    failed_count=$(printf '%s\n' "$failed_units" | grep -c '[^[:space:]]')

    if [ "$failed_count" -gt 0 ]; then
        print_status "error" "${failed_count} failed unit(s)"
        printf '%s\n' "$failed_units" | sed 's/^/     - /'
        issues=$((issues + 1))
    else
        print_status "success" "No failed units"
    fi

    echo ""
    return $issues
}

check_network() {
    echo "=== Network Connectivity ==="
    issues=0

    # Skip gateway check - many routers don't respond to ICMP
    # Just check internet connectivity directly

    # Check internet connectivity
    if ping -c 1 -W 2 google.com >/dev/null 2>&1; then
        print_status "success" "Internet: reachable"
    else
        print_status "error" "Internet: unreachable (check network)"
        issues=$((issues + 1))
    fi
    echo ""
    return $issues
}

check_auto_upgrades() {
    echo "=== Auto-Upgrades Status ==="
    
    # Only check on Debian-based systems (unattended-upgrades is Debian-specific)
    if [ "$OS_TYPE" != "debian" ]; then
        print_status "warning" "Auto-upgrades check only available on Debian"
        echo ""
        return 0
    fi
    
    issues_found=0
    
    # Check if unattended-upgrades is installed
    if ! dpkg -l 2>/dev/null | grep -q "unattended-upgrades"; then
        print_status "error" "unattended-upgrades package not installed"
        issues_found=$((issues_found + 1))
    else
        # Check if service is enabled and running
        if ! systemctl is-enabled unattended-upgrades.service >/dev/null 2>&1; then
            print_status "error" "unattended-upgrades service not enabled"
            issues_found=$((issues_found + 1))
        elif ! systemctl is-active unattended-upgrades.service >/dev/null 2>&1; then
            print_status "error" "unattended-upgrades service not running"
            issues_found=$((issues_found + 1))
        else
            print_status "success" "unattended-upgrades service: running"
        fi
        
        # Check for recent activity - ALERT if no activity for 7+ days
        log_dir="/var/log/unattended-upgrades"
        log_file="$log_dir/unattended-upgrades.log"
        STALE_DAYS=7

        # The directory is `root:adm 0750`, and the infrastructure user is not
        # in `adm` on any host bootstrap created — measured on cwwk, unifi-lxc
        # and agent-lxc. `[ -f "$log_file" ]` is then false because the
        # directory cannot be traversed, and this check used to report the log
        # as missing: a permission error dressed up as a misconfiguration, on
        # three healthy hosts, every 15 minutes once the run can fail.
        #
        # So separate the two. "Cannot see it" is a real gap in coverage and is
        # reported as a warning; it is not evidence that upgrades are broken,
        # and it must not page. "Genuinely absent" and "genuinely stale" still
        # fail, exactly as before.
        if [ ! -d "$log_dir" ]; then
            print_status "error" "Upgrade log directory $log_dir not found - unattended-upgrades may not be configured"
            issues_found=$((issues_found + 1))
        elif [ ! -r "$log_dir" ] || [ ! -x "$log_dir" ]; then
            dir_mode=$(ls -ld "$log_dir" 2>/dev/null | awk '{print $1, $3, $4}')
            print_status "warning" "Upgrade log unreadable as $(id -un) (${dir_mode:-permission denied}) - cannot verify freshness; add the user to 'adm' to close this"
        elif [ -f "$log_file" ] && [ ! -r "$log_file" ]; then
            print_status "warning" "Upgrade log $log_file not readable as $(id -un) - cannot verify freshness"
        elif [ -f "$log_file" ]; then
            # Find the most recent "Starting unattended upgrades" entry
            last_run_line=$(grep "Starting unattended upgrades script" "$log_file" 2>/dev/null | tail -1)
            
            if [ -n "$last_run_line" ]; then
                # Extract date from log entry (format: 2026-01-11 06:12:56,369)
                last_run_date=$(echo "$last_run_line" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -1)
                
                if [ -n "$last_run_date" ]; then
                    # Calculate days since last run (POSIX-compatible)
                    current_epoch=$(date +%s)
                    # Try GNU date first, then BSD date
                    last_epoch=$(date -d "$last_run_date" +%s 2>/dev/null || date -jf "%Y-%m-%d" "$last_run_date" +%s 2>/dev/null)
                    
                    if [ -n "$last_epoch" ]; then
                        days_since=$(( (current_epoch - last_epoch) / 86400 ))
                        
                        if [ "$days_since" -ge "$STALE_DAYS" ]; then
                            print_status "error" "No upgrades for ${days_since} days (last: ${last_run_date}) - ACTION REQUIRED"
                            issues_found=$((issues_found + 1))
                        elif [ "$days_since" -ge 2 ]; then
                            print_status "warning" "Last upgrade: ${last_run_date} (${days_since} days ago)"
                        else
                            print_status "success" "Last upgrade: ${last_run_date}"
                        fi
                    else
                        print_status "warning" "Could not parse last upgrade date"
                    fi
                else
                    print_status "warning" "Could not find upgrade date in logs"
                fi
            else
                print_status "error" "No upgrade activity found in logs - ACTION REQUIRED"
                issues_found=$((issues_found + 1))
            fi
        else
            print_status "error" "Upgrade log not found - unattended-upgrades may not be configured"
            issues_found=$((issues_found + 1))
        fi
        
        # Check configuration files exist
        if [ ! -f /etc/apt/apt.conf.d/20auto-upgrades ] || [ ! -f /etc/apt/apt.conf.d/50unattended-upgrades ]; then
            print_status "error" "Missing auto-upgrade configuration files"
            issues_found=$((issues_found + 1))
        else
            # Check if upgrades are enabled in config
            if ! grep -q 'APT::Periodic::Unattended-Upgrade "1"' /etc/apt/apt.conf.d/20auto-upgrades 2>/dev/null; then
                print_status "error" "Unattended upgrades not enabled in config"
                issues_found=$((issues_found + 1))
            else
                print_status "success" "Configuration: valid"
            fi
        fi
        
        # Note: We intentionally do NOT alert on pending update counts
        # Pending updates naturally accumulate between daily runs - this is normal
        pending=$(apt-get --simulate upgrade 2>/dev/null | grep -c "^Inst")
        pending=${pending:-0}
        print_status "success" "Pending updates: $pending (informational)"
    fi
    
    echo ""
    return $issues_found
}

# Handle command line arguments
case "${1:-}" in
    --version)
        echo "POSIX System Health Check v1.0"
        exit 0
        ;;
    --test)
        echo "Test mode - checking script functionality"
        print_status "success" "Script is executable and functioning"
        exit 0
        ;;
    --help)
        echo "Usage: $0 [--version|--test|--help]"
        echo "  --version  Show version information"
        echo "  --test     Run test mode"
        echo "  --help     Show this help message"
        exit 0
        ;;
esac

# Main execution
echo "=============================="
echo "System Health Check"
echo "Host: $(hostname)"
echo "OS: $OS_TYPE"
echo "Date: $(date)"
echo "=============================="
echo ""

# Each check returns the number of failures it found. They are summed rather
# than short-circuited so that one fault does not hide the rest — the report is
# as complete as it was before, it just now also *reports*.
#
# Until 2026-08 this was a bare list of calls with no aggregation and no final
# `exit`. A script's status is that of its last command, which was an `echo`,
# so it exited 0 no matter what it found. Every ❌ printed correctly, and
# enhanced_monitoring_wrapper — which alerts only on a non-zero status — never
# raised one, on any host, ever.
total_issues=0

check_uptime;         total_issues=$((total_issues + $?))
check_disk_usage;     total_issues=$((total_issues + $?))
check_memory;         total_issues=$((total_issues + $?))
check_load;           total_issues=$((total_issues + $?))
check_services;       total_issues=$((total_issues + $?))
check_failed_units;   total_issues=$((total_issues + $?))
check_network;        total_issues=$((total_issues + $?))
check_auto_upgrades;  total_issues=$((total_issues + $?))

echo "=============================="
if [ "$total_issues" -gt 0 ]; then
    print_status "error" "Health check completed - ${total_issues} issue(s) found"
    echo "=============================="
    # Deliberately `exit 1`, not `exit $total_issues`: an exit status is taken
    # modulo 256, so a host with exactly 256 issues would report success.
    exit 1
fi

print_status "success" "Health check completed - no issues"
echo "=============================="
exit 0
